"""empty message

Revision ID: 87259786f051
Revises: 
Create Date: 2022-05-19 21:17:50.927488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87259786f051'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('uid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'plants', 'users', ['uid'], ['id'])
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=False))
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=10), nullable=False))
    op.drop_column('users', 'confirmed')
    op.drop_column('users', 'password_hash')
    op.drop_constraint(None, 'plants', type_='foreignkey')
    op.drop_column('plants', 'uid')
    # ### end Alembic commands ###
